Comment out the exmples_dir key, because there is no example for this SDK yet. Otherwise, it causes error like:
genmk-sdk-cpuxm.py --gmb_syncto=D:/wt/mm_snprintf/sdkout buildsdk.ini
Traceback (most recent call last):
  File "D:\GMU\GMU-main\umake_cmd\wincmd\genmk-sdk-cpuxm.py", line 149, in <module>
    ret = main()
  File "D:\GMU\GMU-main\umake_cmd\wincmd\genmk-sdk-cpuxm.py", line 139, in main
    CopyExamples()
  File "D:\GMU\GMU-main\umake_cmd\wincmd\genmk-sdk-cpuxm.py", line 72, in CopyExamples
    shutil.copytree(examples_dir, dirDest, ignore=shutil.ignore_patterns('.svn', '.hg'))
  File "D:\Python27\lib\shutil.py", line 171, in copytree
    names = os.listdir(src)
WindowsError: [Error 3] The system cannot find the path specified: 'D:\\wt\\mm_snprintf\\examples/*.*'