I give up, WinCE missing quite many APIs.
../mswin/FlexiInfobox.cpp(254) : error C2065: 'STM_SETICON' : undeclared identifier
../mswin/FlexiInfobox.cpp(496) : error C3861: 'ShowScrollBar': identifier not found
../mswin/FlexiInfobox.cpp(716) : error C2061: syntax error : identifier 'PMINMAXINFO'
../mswin/FlexiInfobox.cpp(910) : error C3861: 'Beep': identifier not found
../mswin/FlexiInfobox.cpp(932) : error C2065: 'WM_GETMINMAXINFO' : undeclared identifier
../mswin/FlexiInfobox.cpp(932) : error C2065: 'LPMINMAXINFO' : undeclared identifier
../mswin/FlexiInfobox.cpp(932) : error C2065: 'LPMINMAXINFO' : undeclared identifier
../mswin/FlexiInfobox.cpp(968) : error C2065: 'IDI_INFORMATION' : undeclared identifier
../mswin/FlexiInfobox.cpp(970) : error C2065: 'IDI_EXCLAMATION' : undeclared identifier