A tiny fix for VC2010: Now do not force convert `_cxx_delete_tag_1<PTR_TYPE>` to `void*`. (No problem on VC2015)
If we did that VC2010 SP1 compiler blames:

EnsureClnup.h(147): error C2440: 'type cast' : cannot convert from 'void (__cdecl *)(PTR_TYPE)' to 'void *'

That meant: VC2010 does not allow convert a templated-argument-constructed function's address to `void*`.

[2026-06-13] I encounter this when compiling D:\gitw\bookcode-mswin\PSSA2000\03-TimeService\03-TimeService.vcxproj